import type { CadDocument, CadEntity } from './autocad-llm-sync.types';

/**
 * Convert JSON CAD document to AutoCAD SCR script format
 */
export function jsonToScr(document: CadDocument): string {
  const commands: string[] = [];
  
  // Add header comment
  commands.push('; AutoCAD Script generated by AutoCAD LLM Sync');
  commands.push('; Generated: ' + new Date().toISOString());
  commands.push('');
  
  // Process each entity
  for (const entity of document.entities) {
    const command = entityToScr(entity);
    if (command) {
      commands.push(command);
    }
  }
  
  // Add zoom extents at the end
  commands.push('');
  commands.push('_ZOOM _E');
  commands.push('');
  
  return commands.join('\n');
}

/**
 * Convert a single entity to SCR command
 */
function entityToScr(entity: CadEntity): string | null {
  switch (entity.type) {
    case 'LINE':
      return lineToScr(entity);
    case 'INSERT':
      return insertToScr(entity);
    case 'CIRCLE':
      return circleToScr(entity);
    case 'POLYLINE':
    case 'LWPOLYLINE':
      return polylineToScr(entity);
    default:
      return null; // Unsupported entity type
  }
}

/**
 * Convert LINE entity to SCR command
 * Format: _LINE x1,y1 x2,y2
 */
function lineToScr(entity: CadEntity): string {
  const start = entity.start || [0, 0, 0];
  const end = entity.end || [0, 0, 0];
  
  // Set layer if not default
  let command = '';
  if (entity.layer && entity.layer !== '0') {
    command += `_LAYER Set "${entity.layer}"\n`;
  }
  
  // Use 2D coordinates (x,y) for simplicity
  command += `_LINE ${start[0]},${start[1]} ${end[0]},${end[1]}\n`;
  
  // Add Z coordinate as comment if present
  if (start[2] !== 0 || end[2] !== 0) {
    command += `; Z coordinates: start=${start[2]}, end=${end[2]}`;
  }
  
  return command;
}

/**
 * Convert INSERT entity to SCR command
 * Format: _-INSERT "BlockName" X,Y ScaleX ScaleY Rotation
 */
function insertToScr(entity: CadEntity): string {
  const insertionPoint = entity.insertion_point || [0, 0, 0];
  const scale = entity.scale || [1, 1, 1];
  const rotation = entity.rotation || 0;
  const blockName = entity.block || 'UNKNOWN';
  
  // Set layer if not default
  let command = '';
  if (entity.layer && entity.layer !== '0') {
    command += `_LAYER Set "${entity.layer}"\n`;
  }
  
  // Insert block
  command += `_-INSERT "${blockName}" ${insertionPoint[0]},${insertionPoint[1]} ${scale[0]} ${scale[1]} ${rotation}`;
  
  // Add Z coordinate as comment if present
  if (insertionPoint[2] !== 0) {
    command += `\n; Z coordinate: ${insertionPoint[2]}`;
  }
  
  return command;
}

/**
 * Convert CIRCLE entity to SCR command
 * Format: _CIRCLE centerX,centerY radius
 */
function circleToScr(entity: CadEntity): string {
  const center = entity.center || { x: 0, y: 0, z: 0 };
  const radius = entity.radius || 1;
  
  // Set layer if not default
  let command = '';
  if (entity.layer && entity.layer !== '0') {
    command += `_LAYER Set "${entity.layer}"\n`;
  }
  
  command += `_CIRCLE ${center.x},${center.y} ${radius}`;
  
  // Add Z coordinate as comment if present
  if (center.z !== 0) {
    command += `\n; Z coordinate: ${center.z}`;
  }
  
  return command;
}

/**
 * Convert POLYLINE/LWPOLYLINE entity to SCR command
 * Format: _PLINE x1,y1 x2,y2 ... (close if shape)
 */
function polylineToScr(entity: CadEntity): string {
  const vertices = entity.vertices || [];
  
  if (vertices.length === 0) {
    return '';
  }
  
  // Set layer if not default
  let command = '';
  if (entity.layer && entity.layer !== '0') {
    command += `_LAYER Set "${entity.layer}"\n`;
  }
  
  // Start polyline
  command += '_PLINE';
  
  // Add vertices
  for (const vertex of vertices) {
    command += ` ${vertex.x},${vertex.y}`;
  }
  
  // Close if shape
  if (entity.shape) {
    command += ' C';
  }
  
  command += '\n';
  
  return command;
}

